version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: ec2-user
      
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 300
      runas: ec2-user
