# Generated by Django 2.0 on 2018-01-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterField(
            model_name='blogauthor',
            name='bio',
            field=models.TextField(help_text='Enter your bio details here.', max_length=400),
        ),
    ]
